### ISSUE TITLE
Urobiom package terms 

### ISSUE THREAD

**Issue by only1chunts** [GenomicsStandardsConsortium/mixs#293]
The Urobiome package will include the following terms that are reused from other packages, we need to check the definitions are all appropriate for their usage here (tick box when checked):

* [ ] MIXS:0000255 - host_age
* [ ] MIXS:0000811 - host_sex
* [ ] MIXS:0000895 - ethnicity
* [ ] MIXS:0000317 - host_body_mass_index
* [ ] MIXS:0001106 - ph_meth
* [ ] MIXS:0000010 - geo_loc_name
* [ ] MIXS:0000009 - lat_lon
* [ ] MIXS:0000869 - host_diet
* [ ] MIXS:0000011 - collection_date
* [ ] MIXS:0000116 - samp_store_dur
* [ ] MIXS:0000110 - samp_store_temp
* [ ] MIXS:0000111 - samp_vol_we_dna_ext

Below is the list of new terms being suggested, each have their own GitHub tickets:
* [ ] - host_gender_identity #262 
* [ ] - race #263
* [ ] - menstrual_status #264
* [ ] - suppl_hormone #265 
* [ ] - lmp #266 
* [ ] - contraception #267
* [ ] - recent_abx #268
* [ ] - recent_surgery #269
* [ ] - gu_surgery #270 
* [ ] - gu_implant #271
* [ ] - diabetes #272
* [ ] - comorbidities #273
* [ ] - immunosuppressant_med #274
* [ ] - gu_abnormal #275
* [ ] - gu_recurrent_infection #276
* [ ] - gu_instrumentation #277
* [ ] - birth_details #278
* [ ] - urine_ph #279
* [ ] - urine_spec_grav #280
* [ ] - urine_leuk #281
* [ ] - urine_blood #282
* [ ] - urine_collect_method #283
* [ ] - month_collected #284
* [ ] - sexual_activity #285
* [ ] - last_intercourse #286
* [ ] - samp_freeze_interval #287
* [ ] - samp_preservative #288
* [ ] - dna_extraction #289 
* [ ] - samp_dna_conc #290 
* [ ] - seq_method #291
* [ ] - samp_protocol #292

**Comment by lakarstens** [comment]
These existing terms have been reviewed and are ok to reuse as-is from other packages:

- [X]  MIXS:0000895 - ethnicity
- [X]  MIXS:0000317 - host_body_mass_index
- [X]  MIXS:0000010 - geo_loc_name
- [X]  MIXS:0000009 - lat_lon
- [X]  MIXS:0000869 - host_diet
- [X]  MIXS:0000011 - collection_date
- [X]  MIXS:0000116 - samp_store_dur
- [X]  MIXS:0000110 - samp_store_temp
- [X]  MIXS:0000111 - samp_vol_we_dna_ext

For these, it would be good to have an example that is relevant for the urobiome research community:

- [ ]  MIXS:0001106 - ph_meth - relevant examples: pH meter; urinalysis dipstick
- [ ]  MIXS:0000255 - host_age - relevant examples: 58 years; 30 months

**Comment by lakarstens** [comment]
Below is the list of new terms being suggested, each have their own GitHub tickets:
Checked indicates the term has been discussed and details added to individual tickets

- [X]  - host_gender_identity https://github.com/GenomicsStandardsConsortium/mixs/issues/262
- [X]  - race https://github.com/GenomicsStandardsConsortium/mixs/issues/263
- [X]  - menstrual_status https://github.com/GenomicsStandardsConsortium/mixs/issues/264
- [X]  - suppl_hormone https://github.com/GenomicsStandardsConsortium/mixs/issues/265
- [X]  - lmp https://github.com/GenomicsStandardsConsortium/mixs/issues/266
- [X]  - contraception https://github.com/GenomicsStandardsConsortium/mixs/issues/267
- [X]  - recent_abx https://github.com/GenomicsStandardsConsortium/mixs/issues/268
- [ ]  - recent_surgery https://github.com/GenomicsStandardsConsortium/mixs/issues/269
- [ ]  - gu_surgery https://github.com/GenomicsStandardsConsortium/mixs/issues/270
- [ ]  - gu_implant https://github.com/GenomicsStandardsConsortium/mixs/issues/271
- [ ]  - diabetes https://github.com/GenomicsStandardsConsortium/mixs/issues/272
- [ ]  - comorbidities https://github.com/GenomicsStandardsConsortium/mixs/issues/273
- [ ]  - immunosuppressant_med https://github.com/GenomicsStandardsConsortium/mixs/issues/274
- [ ]  - gu_abnormal https://github.com/GenomicsStandardsConsortium/mixs/issues/275
- [ ]  - gu_recurrent_infection https://github.com/GenomicsStandardsConsortium/mixs/issues/276
- [ ]  - gu_instrumentation https://github.com/GenomicsStandardsConsortium/mixs/issues/277
- [ ]  - birth_details https://github.com/GenomicsStandardsConsortium/mixs/issues/278
- [ ]  - urine_ph https://github.com/GenomicsStandardsConsortium/mixs/issues/279
- [ ]  - urine_spec_grav https://github.com/GenomicsStandardsConsortium/mixs/issues/280
- [ ]  - urine_leuk https://github.com/GenomicsStandardsConsortium/mixs/issues/281
- [ ]  - urine_blood https://github.com/GenomicsStandardsConsortium/mixs/issues/282
- [ ]  - urine_collect_method https://github.com/GenomicsStandardsConsortium/mixs/issues/283
- [ ]  - month_collected https://github.com/GenomicsStandardsConsortium/mixs/issues/284
- [ ]  - sexual_activity https://github.com/GenomicsStandardsConsortium/mixs/issues/285
- [ ]  - last_intercourse https://github.com/GenomicsStandardsConsortium/mixs/issues/286
- [ ]  - samp_freeze_interval https://github.com/GenomicsStandardsConsortium/mixs/issues/287
- [ ]  - samp_preservative https://github.com/GenomicsStandardsConsortium/mixs/issues/288
- [ ]  - dna_extraction https://github.com/GenomicsStandardsConsortium/mixs/issues/289
- [ ]  - samp_dna_conc https://github.com/GenomicsStandardsConsortium/mixs/issues/290
- [ ]  - seq_method https://github.com/GenomicsStandardsConsortium/mixs/issues/291
- [ ]  - samp_protocol https://github.com/GenomicsStandardsConsortium/mixs/issues/292

**Comment by mslarae13** [comment]
Hi @lakarstens ! I'm working on a summary of MIxS progress since the last meeting. Do you have an update on the urobiom package?
I know we need to release it when v7 comes out, any updates on your end? Term finalization or a publication?
