### ISSUE TITLE
Master issue for problematic enumerations

### ISSUE THREAD

**Issue by turbomam** [GenomicsStandardsConsortium/mixs#367]
- [ ] add_recov_method_enum "other;{timestamp}"
- [ ] compl_score "low;{percentage}"
- [ ] contam_screen_param_enum "combination;{text"
- [ ] floor_finish_mat_enum "none;specify unfinished"
- [ ] food_quality_date_enum "use by; date"
- [ ] pres_animal_insect_enum "other;{integer}"

**Comment by turbomam** [comment]
many of these could still be improved by coming up with more explicit policies for use cases
