### ISSUE TITLE
SIP-MIMS & SIP-MIMARKS checklist addition

### ISSUE THREAD

**Issue by mslarae13** [GenomicsStandardsConsortium/mixs#575]
Collection of issues for addition to MIxS to create SIP checklist (SIP-MIMS & SIP-MIMARKS)

- [ ] New term proposal : isotope
- [ ] New term proposal : isotopologue
- [ ] New term proposal :isotopolog_label
- [ ] New term proposal :isotopolog_approach
- [ ] New term proposal :gradient_position
- [ ] New term proposal :gradient_pos_density
- [ ] New term proposal :gradient_pos_rel_am
- [ ] New term proposal :sip_method
- [ ] Check for term update :source_mat_id
- [ ] New term proposal :isotopolog_atom_per
- [ ] New term proposal :isotopolog_atom_pos
- [ ] New term proposal :isotopolog_dose
- [ ] New term proposal :nucleobase_atom_perc
- [ ] New term proposal :isotopolog_incu_time
- [ ] New term proposal :internal_standard

**Comment by mslarae13** [comment]
source_mat_ID was supposed to link to the sample that was collected in the field / experimental sample. 
- should be these samples came from the same soil

**Comment by simpso91** [comment]
Okay! source_mat_ID may not be appropriate for this then. 
Is there an existing MIxS field that fits this better? Otherwise, we can use a new term (we briefly talked about prefractionation_ID ?)

**Comment by mslarae13** [comment]
from my perspective, source_mat_id is correct .. @only1chunts curious on your thoughts.

We need to be able to say SIP sample or fractionated DNA 1,2,and 3 all came from soil A.

**Comment by mslarae13** [comment]
elution volume and DNA concentration request for calculating concentration 
DNA concentration needs added. To discuss
To do: check if elution volume exists.

**Comment by mslarae13** [comment]
@only1chunts  I've looked through GSC's checklists and extensions and didn't see a DNA concentration slot or elution volume. I can make 2 more issues to add these, but i wanted to check with you on how best to do this. 

These 2 terms seem valuable to the other checklists. Not just MISIP. Should I still put them in this one?

Also, FYI, I will likely miss the compliance and interoperability call unfortunately. I have a week long training to attend. Do you know if it's still scheduled for the 26th or might it be moved?

**Comment by lakarstens** [comment]
@mslarae13 - we also requested a term for dna concentration for the urobiome package. Details are in https://github.com/GenomicsStandardsConsortium/mixs/issues/290

**Comment by mslarae13** [comment]
@only1chunts should we make an issue for source_mat_id?

**Comment by only1chunts** [comment]
Until we reach a point in the Link-ML work where multiple checklists and extensions can be combined we probably need to consider these are multiple (3) new checklists, e.g SIP-MIMS (or maybe it should be MIMS-SIP? ) and SIP-MIMARKS-Survey and SIP-MIMARKS-Cultured, (or does the SIP part only relevant for one of those?)
